### ISSUE TITLE
Registration emails aren't coming through.

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#11]
This user claims they can't receive the registration email:  https://twitter.com/satoBit/status/647155436211314688

**Comment by engren** [comment]
Confirmed! We were early to add IPv6 configuration on the server. Google is picky about how the IPv6 and DNS is implemented, and we just went half way in preparation. (PTR in place, A pointer missing).

This is being fixed right now, and all non-delivered activation e-mails will be resent.

**Comment by engren** [comment]
Disabled IPv6 for now. DNS servers have cached the NX reply for AAAA.

We will add IPv6 within 2 weeks time, once we are certain all caches are cleared.
