### ISSUE TITLE
The notification icons aren't accurate

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#18]
![screen shot 2015-10-19 at 12 35 45 am](https://cloud.githubusercontent.com/assets/2718019/10564730/81ba5d38-75f9-11e5-8181-ca64fbff9a77.png)

**Comment by engren** [comment]
Not following - what is not accurate? One is alerts/notifications with a bell, and the other is the mail inbox with a letter icon? Please clarify! :-)

**Comment by engren** [comment]
Clarified!

When messages are held back, notifications are still showing for the new messages - but no messages are delivered to the inbox. Sorted this by increasing the message size from 50 messages to 1000.

Will expunge unread messages older than a year automatially.
