### ISSUE TITLE
Notification emails are not arriving for some users.

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#19]
![screen shot 2015-10-19 at 1 17 55 pm](https://cloud.githubusercontent.com/assets/2718019/10569621/f4916828-7663-11e5-98f8-b5ba3bc17a35.png)

**Comment by engren** [comment]
Please mail hans@bitcoin.com and include the e-mail address that is givng issues, and I will investigate why this happens.

**Comment by engren** [comment]
Seems related to the DNS issue mentioned earlier. Closing for now.
