### ISSUE TITLE
More email notification troubles

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#21]
"Hey, Roger! I messaged the admin contact on forum.bitcoin.com a few days ago(not sure if it is you) - I'm not receiving activation emails to baklava@mandrik.com. Not sure what's up. I set up my username as Mandrik."

**Comment by engren** [comment]
Issue confirmed. We are missing DNS reverse on the IP used for outgoing connections.

Escalated to DNS admin for fixing.

**Comment by engren** [comment]
This was fixed merely hours after the report.
