### ISSUE TITLE
The social media sharing buttons are not appearing on the forum

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#28]
Here is what I see:  
![screen shot 2015-11-02 at 11 27 44 pm](https://cloud.githubusercontent.com/assets/2718019/10884079/5c966260-81b9-11e5-8118-794ce8413690.png)

**Comment by bitcoinstore** [comment]
I think having this working could really help the AMA sessions get even more steam.

**Comment by engren** [comment]
This has been fixed and activated on all posts.
