### ISSUE TITLE
Cookie acceptance policy pop up

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#30]
Sooooo many people have been contacting me complaining about the cookie pop up acceptance thing.
Can we remove it from the site?

People really hate it!

**Comment by engren** [comment]
Sorry,

At most I can remove it for IPs not originating from inside the European Union, but this will cause slightly slower pageloads overall as we need to geo-IP everything.

http://www.cookielaw.org/the-cookie-law/

**Comment by bitcoinstore** [comment]
According to the link:  "If you don't comply you risk enforcement action from regulators, which in the UK means The Information Commissioners' Office (ICO). In exceptional cases this can mean a fine."

I'm fine with removing it completely and just paying a fine if we need to some day.

**Comment by engren** [comment]
As you wish. The compliance module for "the cookie law" has been disabled.
