### ISSUE TITLE
The twitter preview location is strange again

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#31]
Example here:  https://forum.bitcoin.com/ama-ask-me-anything-f69/im-juan-garavaglia-rootstock-iom-ask-me-anything-t2051.html#p5526

**Comment by engren** [comment]
Twitter preview is inputted right where the twitter link is. There is no line feed automatically put in place, and this happened because the twitter link was straight after a line of text.

Will modify the plugin to insert an automatic linefeed to avoid this.

**Comment by engren** [comment]
Code has been updated, and now inserts an unconditional linefeed to make sure it's always on a line of its' own.
