### ISSUE TITLE
Bitcoin address QR codes

### ISSUE THREAD

**Issue by bitcoinstore** [BTCForum/suggestions#35]
Would it be possible to have the Bitcoin addresses in peoples profile display a QR code when someone mouses over them? Or, alternatively,  change them to link to the correct address on Blockchain.info
Per this user request:  https://forum.bitcoin.com/bitcoin-discussion/any-chance-for-integrating-btc-tipping-feature-in-future-t2226.html#p6310

**Comment by engren** [comment]
This has been partially added - currently only available when viewing threads.

Working on a link within the profile aswell.

**Comment by engren** [comment]
QR codes are now shown when viewing a profile, and it's linked to Blockchain.
